Commerce 13 and PSD2 (#16)
Geta/Netaxept pull request #17
Opened 2021-04-22 13:39 UTC by svenrog

Upgrade Nets to Commerce 13 and addressing #16.

2021-04-22 17:03 UTC, patkleef requested changes

2021-04-23 08:23 UTC, svenrog commented on Test/Test.Browser/app.config
> +    <add key="Netaxept:MerchantId" value="12002339"/>
Those credentials should only exist inside of the preview of this comment now.

2021-04-23 08:28 UTC, patkleef approved these changes

2021-04-26 11:42 UTC, svenrog commented
Closing this due to busted CI.

2021-04-26 11:42 UTC, closed without merging